---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: swarm-tunnel
  namespace: xnet

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: swarm-tunnel
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: swarm-tunnel
subjects:
- kind: ServiceAccount
  name: swarm-tunnel
  namespace: xnet
roleRef:
  kind: ClusterRole
  name: swarm-tunnel
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: swarm-server
  namespace: xnet
  labels:
    app: swarm-server
spec:
  selector:
    app: swarm-server
  type: NodePort
  ports:
  - name: swarm-server
    port: 8080
    nodePort: 30888
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: swarm-server
  namespace: xnet
  labels:
    app: swarm-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swarm-server
  template:
    metadata:
      labels:
        app: swarm-server
    spec:
      serviceAccountName: swarm-tunnel
      nodeSelector:
        kubernetes.io/hostname: "master"
      containers:
      - name: swarm-server
        image: swarm-server:v1.0
        imagePullPolicy: IfNotPresent
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: swarm-client
  namespace: xnet
  labels:
    app: swarm-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swarm-client
  template:
    metadata:
      labels:
        app: swarm-client
    spec:
      serviceAccountName: swarm-tunnel
      nodeSelector:
        kubernetes.io/hostname: "master"
      containers:
      - name: swarm-client
        image: swarm-client:v1.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: sshkey
          mountPath: /root/.ssh
      volumes:
      - name: sshkey
        hostPath:
          path: /root/.ssh